# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ab5d942d6121d39fdeb15f40d8a01fe71b41c25c2c14651102bfe39f2032d8d6c3a270e9639951f0046d1f53390a627ac585be58ddccae562b7e69bb1ac6cbdb

test:
  secret_key_base: ba72ad4ef19c32d88a90d1e767321718fe63adcc63fdcecfa528d08c7a46364f516352ef3474f5df1e262cb41de1b4068c2339958a00cd40bc6dd27c31f17ab6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
